{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plik.fullname" . }}
  labels:
    {{- include "plik.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.plikd.GoogleApiSecret }}
  PLIKD_GOOGLE_API_SECRET: {{ .Values.plikd.GoogleApiSecret | quote }}
  {{- end }}
  {{- if .Values.plikd.OvhApiSecret }}
  PLIKD_OVH_API_SECRET: {{ .Values.plikd.OvhApiSecret | quote }}
  {{- end }}
  {{- if .Values.plikd.OIDCClientSecret }}
  PLIKD_OIDC_CLIENT_SECRET: {{ .Values.plikd.OIDCClientSecret | quote }}
  {{- end }}
  
  {{- /* Handle DataBackendConfig sensitive data */}}
  {{- $dataBackendSecret := dict }}
  {{- if .Values.plikd.DataBackendConfig.SecretAccessKey }}
  {{- $_ := set $dataBackendSecret "SecretAccessKey" .Values.plikd.DataBackendConfig.SecretAccessKey }}
  {{- end }}
  {{- if .Values.plikd.DataBackendConfig.ApiKey }}
  {{- $_ := set $dataBackendSecret "ApiKey" .Values.plikd.DataBackendConfig.ApiKey }}
  {{- end }}
  {{- if $dataBackendSecret }}
  PLIKD_DATA_BACKEND_CONFIG: {{ $dataBackendSecret | toJson | quote }}
  {{- end }}

  {{- /* Handle MetadataBackendConfig sensitive data */}}
  {{- $metadataBackendSecret := dict }}
  {{- if .Values.plikd.MetadataBackendConfig.Password }}
  {{- $_ := set $metadataBackendSecret "Password" .Values.plikd.MetadataBackendConfig.Password }}
  {{- end }}
  {{- if $metadataBackendSecret }}
  PLIKD_METADATA_BACKEND_CONFIG: {{ $metadataBackendSecret | toJson | quote }}
  {{- end }}
{{- end }}
